server: {
  conn: "0.0.0.0:5000"
}

database: {
  dbms: postgres,
  #host: postgres,
  host: localhost,
  port: 5432,
  user: forum_user,
  password: forum1234,
  name: forum_db,
  sslmode: disable,
  connections: 100,
}